//
//  SMSOTPController.h
//  M2Factor
//
//  This file was automatically generated for 2Factor by APIMATIC BETA v2.0 on 02/18/2016
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "CheckSmsBalanceModel.h"
#import "SendingSmsOtpAutoGeneratedOtpModel.h"
#import "SendingSmsOtpModel.h"
#import "VerifyOtpInputModel.h"

@interface SMSOTPController : BaseController

/**
* Completion block definition for asynchronous call to Check SMS Balance */
typedef void (^CompletedGetCheckSMSBalance)(BOOL success, HttpContext* context, CheckSmsBalanceModel* response, NSError* error);

/**
* This endpoint is used to check SMS OTP balance
* @param    apiKey    Required parameter: API Obtained From 2Factor.in
*/
- (void) getCheckSMSBalanceAsyncWithApiKey:(NSString*) apiKey
                completionBlock:(CompletedGetCheckSMSBalance) onCompleted;

/**
* Completion block definition for asynchronous call to Sending SMS OTP ( Auto Generated OTP ) */
typedef void (^CompletedGetSendingSMSOTPAutoGeneratedOTP)(BOOL success, HttpContext* context, SendingSmsOtpAutoGeneratedOtpModel* response, NSError* error);

/**
* This endpoint is used to send Auto Generated SMS OTP to India
* @param    apiKey    Required parameter: API Obtained From 2Factor.in
* @param    phoneNumber    Required parameter: 10 Digit Indian Phone Number
*/
- (void) getSendingSMSOTPAutoGeneratedOTPAsyncWithApiKey:(NSString*) apiKey
                phoneNumber:(NSString*) phoneNumber
                completionBlock:(CompletedGetSendingSMSOTPAutoGeneratedOTP) onCompleted;

/**
* Completion block definition for asynchronous call to Sending SMS OTP ( Custom OTP ) */
typedef void (^CompletedGetSendingSMSOTPCustomOTP)(BOOL success, HttpContext* context, SendingSmsOtpModel* response, NSError* error);

/**
* This endpoint is used to send Custom SMS OTP to India
* @param    apiKey    Required parameter: API Obtained From 2Factor.in
* @param    otp    Required parameter: 4-6 Digit ( Numeric ) OTP code to be sent
* @param    phoneNumber    Required parameter: 10 Digit Indian Phone Number
*/
- (void) getSendingSMSOTPCustomOTPAsyncWithApiKey:(NSString*) apiKey
                otp:(NSString*) otp
                phoneNumber:(NSString*) phoneNumber
                completionBlock:(CompletedGetSendingSMSOTPCustomOTP) onCompleted;

/**
* Completion block definition for asynchronous call to Verify SMS OTP Input */
typedef void (^CompletedGetVerifySMSOTPInput)(BOOL success, HttpContext* context, VerifyOtpInputModel* response, NSError* error);

/**
* This endpoint is useful in verifying user entered OTP with sent OTP
* @param    apiKey    Required parameter: API Obtained From 2Factor.in
* @param    otpInput    Required parameter: OTP Value input by end user
* @param    sessionId    Required parameter: Verification session id returned in send OTP step
*/
- (void) getVerifySMSOTPInputAsyncWithApiKey:(NSString*) apiKey
                otpInput:(NSString*) otpInput
                sessionId:(NSString*) sessionId
                completionBlock:(CompletedGetVerifySMSOTPInput) onCompleted;

@end