//
//  VOICEOTPController.m
//  M2Factor
//
//  This file was automatically generated for 2Factor by APIMATIC BETA v2.0 on 02/18/2016
//
#import "VOICEOTPController.h"

@implementation VOICEOTPController

/**
* This endpoint is used to check VOICE OTP balance
* @param    apiKey    Required parameter: Check VOICE OTP Balance
* @return	Returns the CheckVoiceBalanceModel* response from the API call */
- (void) getCheckVoiceBalanceAsyncWithApiKey:(NSString*) apiKey
                completionBlock:(CompletedGetCheckVoiceBalance) onCompleted
{
    //the base uri for api requests
    NSString* baseUri = [NSString stringWithString: (NSString*) Configuration_BaseUri];

    //prepare query string for API call
    NSMutableString* queryBuilder = [NSMutableString stringWithString: baseUri]; 
    [queryBuilder appendString: @"/API/V1/{api_key}/BAL/VOICE"];

    //process optional query parameters
    [APIHelper appendUrl: queryBuilder withTemplateParameters: @{
                    @"api_key": apiKey
                }];

    //validate and preprocess url
    NSString* queryUrl = [APIHelper cleanUrl: queryBuilder];

    //preparing request headers
    NSMutableDictionary* headers = [[NSMutableDictionary alloc] initWithDictionary: @{
        @"user-agent": @"2Factor",
        @"accept": @"application/json"
    }];

    //Remove null values from header collection in order to omit from request
    [APIHelper removeNullValues: headers];


    //prepare the request and fetch response  
    HttpRequest* request = [[self clientInstance] get: ^(HttpRequest* request) 
    { 
        [request setQueryUrl: queryUrl]; //set request url        
        [request setHeaders: headers]; //set request headers

    }];

    //use the instance of the http client to make the actual call
    [[self clientInstance]
     executeAsString: request
     success: ^(id context, HttpResponse *response) {
         //Error handling using HTTP status codes
         NSError* statusError = nil;

         //Error handling using HTTP status codes 
         if((response.statusCode < 200) || (response.statusCode > 206)) //[200,206] = HTTP OK
             statusError = [[APIError alloc] initWithReason: @"HTTP Response Not OK"
                                                    andCode: response.statusCode
                                                    andData: response.rawBody];

         if(statusError != nil)
         {
             //announce completion with failure due to HTTP status code checking
             onCompleted(NO, context, nil, statusError);
         }
         else
         {
             //return response to API caller
             NSString* strResult = [(HttpStringResponse*)response body];
             CheckVoiceBalanceModel* result = (CheckVoiceBalanceModel*) [APIHelper jsonDeserialize: strResult
                toClass: CheckVoiceBalanceModel.class];

 
             //announce completion with success
             onCompleted(YES, context, result, nil);
         }
     } failure:^(id context, NSError *error) {
 
         //announce completion with failure
         onCompleted(NO, context, nil, error);
     }];
}

/**
* This endpoint is used to send Auto Generated VOICE OTP to India
* @param    apiKey    Required parameter: API Obtained From 2Factor.in
* @param    phoneNumber    Required parameter: 10 Digit Indian Phone Number
* @return	Returns the SendingVoiceOtpAutoGeneratedOtpModel* response from the API call */
- (void) getSendingVOICEOTPAutoGeneratedOTPAsyncWithApiKey:(NSString*) apiKey
                phoneNumber:(NSString*) phoneNumber
                completionBlock:(CompletedGetSendingVOICEOTPAutoGeneratedOTP) onCompleted
{
    //the base uri for api requests
    NSString* baseUri = [NSString stringWithString: (NSString*) Configuration_BaseUri];

    //prepare query string for API call
    NSMutableString* queryBuilder = [NSMutableString stringWithString: baseUri]; 
    [queryBuilder appendString: @"/API/V1/{api_key}/VOICE/{phone_number}/AUTOGEN"];

    //process optional query parameters
    [APIHelper appendUrl: queryBuilder withTemplateParameters: @{
                    @"api_key": apiKey,
                    @"phone_number": phoneNumber
                }];

    //validate and preprocess url
    NSString* queryUrl = [APIHelper cleanUrl: queryBuilder];

    //preparing request headers
    NSMutableDictionary* headers = [[NSMutableDictionary alloc] initWithDictionary: @{
        @"user-agent": @"2Factor",
        @"accept": @"application/json"
    }];

    //Remove null values from header collection in order to omit from request
    [APIHelper removeNullValues: headers];


    //prepare the request and fetch response  
    HttpRequest* request = [[self clientInstance] get: ^(HttpRequest* request) 
    { 
        [request setQueryUrl: queryUrl]; //set request url        
        [request setHeaders: headers]; //set request headers

    }];

    //use the instance of the http client to make the actual call
    [[self clientInstance]
     executeAsString: request
     success: ^(id context, HttpResponse *response) {
         //Error handling using HTTP status codes
         NSError* statusError = nil;

         //Error handling using HTTP status codes 
         if((response.statusCode < 200) || (response.statusCode > 206)) //[200,206] = HTTP OK
             statusError = [[APIError alloc] initWithReason: @"HTTP Response Not OK"
                                                    andCode: response.statusCode
                                                    andData: response.rawBody];

         if(statusError != nil)
         {
             //announce completion with failure due to HTTP status code checking
             onCompleted(NO, context, nil, statusError);
         }
         else
         {
             //return response to API caller
             NSString* strResult = [(HttpStringResponse*)response body];
             SendingVoiceOtpAutoGeneratedOtpModel* result = (SendingVoiceOtpAutoGeneratedOtpModel*) [APIHelper jsonDeserialize: strResult
                toClass: SendingVoiceOtpAutoGeneratedOtpModel.class];

 
             //announce completion with success
             onCompleted(YES, context, result, nil);
         }
     } failure:^(id context, NSError *error) {
 
         //announce completion with failure
         onCompleted(NO, context, nil, error);
     }];
}

/**
* This endpoint is used to send VOICE OTP to India
* @param    apiKey    Required parameter: API Obtained From 2Factor.in
* @param    otp    Required parameter: 4 Digit ( Numeric ) OTP code to be sent
* @param    phoneNumber    Required parameter: 10 Digit Indian Phone Number
* @return	Returns the SendingVoiceOtpModel* response from the API call */
- (void) getSendingVoiceOTPCustomOTPAsyncWithApiKey:(NSString*) apiKey
                otp:(int) otp
                phoneNumber:(NSString*) phoneNumber
                completionBlock:(CompletedGetSendingVoiceOTPCustomOTP) onCompleted
{
    //the base uri for api requests
    NSString* baseUri = [NSString stringWithString: (NSString*) Configuration_BaseUri];

    //prepare query string for API call
    NSMutableString* queryBuilder = [NSMutableString stringWithString: baseUri]; 
    [queryBuilder appendString: @"/API/V1/{api_key}/VOICE/{phone_number}/{otp}"];

    //process optional query parameters
    [APIHelper appendUrl: queryBuilder withTemplateParameters: @{
                    @"api_key": apiKey,
                    @"otp": [NSNumber numberWithInteger:otp],
                    @"phone_number": phoneNumber
                }];

    //validate and preprocess url
    NSString* queryUrl = [APIHelper cleanUrl: queryBuilder];

    //preparing request headers
    NSMutableDictionary* headers = [[NSMutableDictionary alloc] initWithDictionary: @{
        @"user-agent": @"2Factor",
        @"accept": @"application/json"
    }];

    //Remove null values from header collection in order to omit from request
    [APIHelper removeNullValues: headers];


    //prepare the request and fetch response  
    HttpRequest* request = [[self clientInstance] get: ^(HttpRequest* request) 
    { 
        [request setQueryUrl: queryUrl]; //set request url        
        [request setHeaders: headers]; //set request headers

    }];

    //use the instance of the http client to make the actual call
    [[self clientInstance]
     executeAsString: request
     success: ^(id context, HttpResponse *response) {
         //Error handling using HTTP status codes
         NSError* statusError = nil;

         //Error handling using HTTP status codes 
         if((response.statusCode < 200) || (response.statusCode > 206)) //[200,206] = HTTP OK
             statusError = [[APIError alloc] initWithReason: @"HTTP Response Not OK"
                                                    andCode: response.statusCode
                                                    andData: response.rawBody];

         if(statusError != nil)
         {
             //announce completion with failure due to HTTP status code checking
             onCompleted(NO, context, nil, statusError);
         }
         else
         {
             //return response to API caller
             NSString* strResult = [(HttpStringResponse*)response body];
             SendingVoiceOtpModel* result = (SendingVoiceOtpModel*) [APIHelper jsonDeserialize: strResult
                toClass: SendingVoiceOtpModel.class];

 
             //announce completion with success
             onCompleted(YES, context, result, nil);
         }
     } failure:^(id context, NSError *error) {
 
         //announce completion with failure
         onCompleted(NO, context, nil, error);
     }];
}

/**
* This endpoint is useful in verifying user entered OTP with sent OTP
* @param    apiKey    Required parameter: API Obtained From 2Factor.in
* @param    otpInput    Required parameter: OTP Value input by end user
* @param    sessionId    Required parameter: Verification session id returned in send OTP step
* @return	Returns the VerifyVoiceOtpInputModel* response from the API call */
- (void) getVerifyVOICEOTPInputAsyncWithApiKey:(NSString*) apiKey
                otpInput:(NSString*) otpInput
                sessionId:(NSString*) sessionId
                completionBlock:(CompletedGetVerifyVOICEOTPInput) onCompleted
{
    //the base uri for api requests
    NSString* baseUri = [NSString stringWithString: (NSString*) Configuration_BaseUri];

    //prepare query string for API call
    NSMutableString* queryBuilder = [NSMutableString stringWithString: baseUri]; 
    [queryBuilder appendString: @"/API/V1/{api_key}/VOICE/VERIFY/{session_id}/{otp_input}"];

    //process optional query parameters
    [APIHelper appendUrl: queryBuilder withTemplateParameters: @{
                    @"api_key": apiKey,
                    @"otp_input": otpInput,
                    @"session_id": sessionId
                }];

    //validate and preprocess url
    NSString* queryUrl = [APIHelper cleanUrl: queryBuilder];

    //preparing request headers
    NSMutableDictionary* headers = [[NSMutableDictionary alloc] initWithDictionary: @{
        @"user-agent": @"2Factor",
        @"accept": @"application/json"
    }];

    //Remove null values from header collection in order to omit from request
    [APIHelper removeNullValues: headers];


    //prepare the request and fetch response  
    HttpRequest* request = [[self clientInstance] get: ^(HttpRequest* request) 
    { 
        [request setQueryUrl: queryUrl]; //set request url        
        [request setHeaders: headers]; //set request headers

    }];

    //use the instance of the http client to make the actual call
    [[self clientInstance]
     executeAsString: request
     success: ^(id context, HttpResponse *response) {
         //Error handling using HTTP status codes
         NSError* statusError = nil;

         //Error handling using HTTP status codes 
         if((response.statusCode < 200) || (response.statusCode > 206)) //[200,206] = HTTP OK
             statusError = [[APIError alloc] initWithReason: @"HTTP Response Not OK"
                                                    andCode: response.statusCode
                                                    andData: response.rawBody];

         if(statusError != nil)
         {
             //announce completion with failure due to HTTP status code checking
             onCompleted(NO, context, nil, statusError);
         }
         else
         {
             //return response to API caller
             NSString* strResult = [(HttpStringResponse*)response body];
             VerifyVoiceOtpInputModel* result = (VerifyVoiceOtpInputModel*) [APIHelper jsonDeserialize: strResult
                toClass: VerifyVoiceOtpInputModel.class];

 
             //announce completion with success
             onCompleted(YES, context, result, nil);
         }
     } failure:^(id context, NSError *error) {
 
         //announce completion with failure
         onCompleted(NO, context, nil, error);
     }];
}


@end