//
//  VOICEOTPController.h
//  M2Factor
//
//  This file was automatically generated for 2Factor by APIMATIC BETA v2.0 on 02/18/2016
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "CheckVoiceBalanceModel.h"
#import "SendingVoiceOtpAutoGeneratedOtpModel.h"
#import "SendingVoiceOtpModel.h"
#import "VerifyVoiceOtpInputModel.h"

@interface VOICEOTPController : BaseController

/**
* Completion block definition for asynchronous call to Check Voice Balance */
typedef void (^CompletedGetCheckVoiceBalance)(BOOL success, HttpContext* context, CheckVoiceBalanceModel* response, NSError* error);

/**
* This endpoint is used to check VOICE OTP balance
* @param    apiKey    Required parameter: Check VOICE OTP Balance
*/
- (void) getCheckVoiceBalanceAsyncWithApiKey:(NSString*) apiKey
                completionBlock:(CompletedGetCheckVoiceBalance) onCompleted;

/**
* Completion block definition for asynchronous call to Sending VOICE OTP ( Auto Generated OTP ) */
typedef void (^CompletedGetSendingVOICEOTPAutoGeneratedOTP)(BOOL success, HttpContext* context, SendingVoiceOtpAutoGeneratedOtpModel* response, NSError* error);

/**
* This endpoint is used to send Auto Generated VOICE OTP to India
* @param    apiKey    Required parameter: API Obtained From 2Factor.in
* @param    phoneNumber    Required parameter: 10 Digit Indian Phone Number
*/
- (void) getSendingVOICEOTPAutoGeneratedOTPAsyncWithApiKey:(NSString*) apiKey
                phoneNumber:(NSString*) phoneNumber
                completionBlock:(CompletedGetSendingVOICEOTPAutoGeneratedOTP) onCompleted;

/**
* Completion block definition for asynchronous call to Sending Voice OTP ( Custom OTP ) */
typedef void (^CompletedGetSendingVoiceOTPCustomOTP)(BOOL success, HttpContext* context, SendingVoiceOtpModel* response, NSError* error);

/**
* This endpoint is used to send VOICE OTP to India
* @param    apiKey    Required parameter: API Obtained From 2Factor.in
* @param    otp    Required parameter: 4 Digit ( Numeric ) OTP code to be sent
* @param    phoneNumber    Required parameter: 10 Digit Indian Phone Number
*/
- (void) getSendingVoiceOTPCustomOTPAsyncWithApiKey:(NSString*) apiKey
                otp:(int) otp
                phoneNumber:(NSString*) phoneNumber
                completionBlock:(CompletedGetSendingVoiceOTPCustomOTP) onCompleted;

/**
* Completion block definition for asynchronous call to Verify VOICE OTP Input */
typedef void (^CompletedGetVerifyVOICEOTPInput)(BOOL success, HttpContext* context, VerifyVoiceOtpInputModel* response, NSError* error);

/**
* This endpoint is useful in verifying user entered OTP with sent OTP
* @param    apiKey    Required parameter: API Obtained From 2Factor.in
* @param    otpInput    Required parameter: OTP Value input by end user
* @param    sessionId    Required parameter: Verification session id returned in send OTP step
*/
- (void) getVerifyVOICEOTPInputAsyncWithApiKey:(NSString*) apiKey
                otpInput:(NSString*) otpInput
                sessionId:(NSString*) sessionId
                completionBlock:(CompletedGetVerifyVOICEOTPInput) onCompleted;

@end